apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-envfrom
  name: secret-envfrom
spec:
  containers:
  - command:
    - sh
    - -c
    - |
      echo "APP_USER=$APP_USER"
      echo "APP_PASSWORD=$APP_PASSWORD"
      sleep 3600
    envFrom:
      - secretRef:
         name: manual-secret
    image: alpine
    name: app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
