apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-keyref
  name: secret-keyref
spec:
  containers:
  - command:
    - sh
    - -c
    - |
      echo "DATABASE_PASSWORD=$DATABASE_PASSWORD"
      sleep 3600
    env:
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: manual-secret
          key: APP_PASSWORD
    image: alpine
    name: app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
