apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-volume
  name: secret-volume
spec:
  volumes:
  - name: secret-data
    secret:
      secretName: manual-secret
  containers:
  - command:
    - sh
    - -c
    - |
      echo "Files:"
      ls -l /etc/secrets
      echo "Username:"
      cat /etc/secrets/APP_USER
      echo
      echo "Password:"
      cat /etc/secrets/APP_PASSWORD
      echo
      sleep 3600
    image: alpine
    name: app
    volumeMounts:
    - name: secret-data
      mountPath: /etc/secrets
      readOnly: true  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
