apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-defaultmode
  name: secret-defaultmode
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: database-env-secret
        defaultMode: 0440
        items:
        - key: DB_USER
          path: username
        - key: DB_PASSWORD
          path: password    
  containers:
  - command:
    - sleep
    - "3600"
    image: alpine
    name: secret-defaultmode
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/database
      readOnly: true
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
