apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: missing-secret-keyref
  name: missing-secret-keyref
spec:
  containers:
  - command:
    - sleep
    - "3600"
    env:
    - name: API_TOKEN
      valueFrom:
        secretKeyRef:
          name: database-env-secret
          key: API_TOKEN  
    image: alpine
    name: missing-secret-keyref
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
