apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: missing-envfrom-secret
  name: missing-envfrom-secret
spec:
  containers:
  - command:
    - sleep
    - "3600"
    envFrom:
      - secretRef:
         name: missing-app-secret
    image: alpine
    name: missing-envfrom-secret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
