apiVersion: v1
data:
  DB_HOST: cG9zdGdyZXMuaW50ZXJuYWw=
  DB_PASSWORD: RmluYWxTZWNyZXQ3ODk=
  DB_PORT: NTQzMg==
  DB_USER: Y2thZHVzZXI=
kind: Secret
metadata:
  creationTimestamp: null
  name: app-db-secret
