apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: final-secret-app
  name: final-secret-app
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: app-db-secret
      items:
       - key: DB_HOST
         path: host
       - key: DB_PORT
         path: port
         mode: 0400    
      defaultMode: 0440    
  containers:
  - command:
    - sleep
    - "3600"
    env:
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: app-db-secret
          key: DB_USER  
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-db-secret
          key: DB_PASSWORD
    image: alpine
    name: final-secret-app
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/database
        readOnly: true  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
