apiVersion: v1
kind: Pod
metadata:
  name: simple-init
spec:
  initContainers:
  - name: init-sleep
    image: busybox:1.36
    command:
      - sh
      - -c 
      - | 
        echo "Init Container started"
        sleep 10
        echo "Init Container finished"
  containers:
  - name: nginx
    image: nginx:latest    
