apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis-app
  name: redis-app
spec:
  containers:
  - image: redis:7
    name: redis-app
    envFrom:
    - configMapRef:
        name: redis-config

    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
