apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: runtime-demo
  name: runtime-demo
spec:
  volumes:
    - name: config-volume
      configMap:
        name: runtime-config  
  containers:
  - command:
    - sh 
    - -c
    - | 
        env | grep -i app_mode
        echo
        cat /etc/config/APP_MODE
        echo
        sleep 3600
    envFrom:
      - configMapRef:
          name: runtime-config
    image: alpine:3.20
    name: app
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
