apiVersion: v1
kind: Pod
metadata:
  name: exercise-2
spec:
  containers:
    - name: myapp
      image: busybox
      command: ["sh", "-c", "env && sleep 3600"]
      envFrom:
        - configMapRef:
            name: configmap-exercise-2 
      