apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tools
    env: dev
    tier: utility
  name: busybox-pod
spec:
  containers:
  - image: busybox:1.37
    name: busybox
    command: ["bin/sh","-c","sleep 3600"]  
