apiVersion: v1
kind: Pod
metadata:
  name: pod-broken-2
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command:
    - sh
    args:
    - -c  
    - |
      echo "Hello CKAD"
      sleep 30
