apiVersion: v1
kind: Pod
metadata:
  name: production-web
spec:
  volumes:
  - name: web-content
    emptyDir: {}
  initContainers:
  - name: content-init
    image: busybox
    volumeMounts:
    - name: web-content
      mountPath: /content
    command: ["bin/sh","-c", "echo CKAD final task > /content/index.html"]    
  containers:
  - image: nginx
    name: web
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 128Mi    
    volumeMounts:
    - name: web-content
      mountPath: /usr/share/nginx/html
    ports:    
    - name: http
      containerPort: 80
    env:    
    - name: APP_ENV
      value: production
    startupProbe:    
      httpGet:
        path: /
        port: http  
      periodSeconds: 2
      failureThreshold: 15
    readinessProbe:
      httpGet:
        path: /
        port: http  
      periodSeconds: 5
      failureThreshold: 2    
    livenessProbe:
      httpGet:
        path: /
        port: http  
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 3    
  - image: busybox
    name: content-reader
    volumeMounts:
    - name: web-content
      mountPath: /content
      readOnly: true
    command: ["bin/sh","-c","sleep 3600"]
