apiVersion: v1
kind: Pod
metadata:
  name: web-logger
spec:
  volumes:
  - name: logs
    emptyDir: {}
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: logs
      mountPath: /var/log/shared
    livenessProbe:    
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5    
  - image: busybox
    name: logger
    volumeMounts:
    - name: logs
      mountPath: /logs
    command: ["bin/sh", "-c", "sleep 3600"]
