apiVersion: v1
kind: Pod
metadata:
  name: app-with-init
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  initContainers:
  - name: init-config
    image: busybox
    command: ["bin/sh", "-c", "echo Configuration loaded > /shared/config.txt"]
    volumeMounts:
    - name: shared-data
      mountPath: /shared  
  containers:
  - image: busybox
    name: app
    volumeMounts:
    - name: shared-data
      mountPath: /shared
    env:    
    - name: APP_MODE
      value: produktion
    command: ["bin/sh", "-c", "sleep 3600"]
    readinessProbe:
      exec:
        command: ["bin/sh", "-c", "cat /shared/config.txt"]

