apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hard-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 
---
apiVersion: v1
kind: Pod
metadata:
  name: hard-pod
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: hard-pvc    
