apiVersion: v1
kind: Pod
metadata:
  name: exercise-3
spec:
  containers:
    - name: myapp
      image: busybox
      command: ["sh", "-c", "env && sleep 3600"]
      env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
             name: secret-exercise-3
             key: API_KEY
      