apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cpu-limit
  name: cpu-limit
spec:
  containers:
  - command:
    - sh
    - -c
    - "while true; do :; done"
    image: alpine:3.22
    name: cpu-limit
    resources:
      requests:
        cpu: "100m"
      limits:
        cpu: "250m"    
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
