apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: impossible-request
  name: impossible-request
spec:
  containers:
  - image: nginx:1.29
    name: impossible-request
    resources:
      requests:
        cpu: "1500m"
        memory:  "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
