apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: limit-only
  name: limit-only
spec:
  containers:
  - image: nginx:1.29
    name: limit-only
    resources:
      limits:
        cpu: "500m"
        memory: "128Mi"  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
