apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: resource-multi
  name: resource-multi
spec:
  containers:
  - image: nginx:1.29
    name: web
    resources: 
      requests:
        cpu: "200m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"    
  - image: alpine:3.22
    name: sidercar
    command:
      - sh
      - -c
      - sleep 3600  
    resources: 
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"    
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
