apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-resources
  name: nginx-resources
spec:
  containers:
  - image: nginx:1.29
    name: nginx-resources
    resources:
      requests:
        cpu: "100m"
        memory: 64Mi
      limits:
        cpu: "250m"    
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
