apiVersion: v1
kind: Pod
metadata:
  name: task-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "echo CKAD >> /data/test.txt && sleep 3600"]
      volumeMounts:
        - name: storage
          mountPath: /data
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: task-pvc    
