apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c", "echo 'persistent data new' >> /data/file.txt; echo; sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data 
  volumes:
    - name: data 
      persistentVolumeClaim:
        claimName: demo-pvc