apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  initContainers:
  - name: init-writer
    image: busybox
    command: ["/bin/sh", "-c", "echo Hello from Init Container > /shared/message.txt;"]  
    volumeMounts:
    - name: shared-data
      mountPath: /shared  

  containers:
  - image: busybox
    name: app
    command: ["/bin/sh", "-c", "sleep 3600"] 
    volumeMounts:
    - name: shared-data
      mountPath: /shared 
