apiVersion: v1
kind: Pod
metadata:
  name: shared-storage
spec:
  volumes:
  - name: shareddir
    emptyDir: {}  
  containers:
  - image: busybox
    name: writer
    command: ["bin/sh", "-c", "echo Hello CKAD > /shared/message.txt; sleep 3600"] 
    volumeMounts:
    - name: shareddir
      mountPath: /shared  
  - image: busybox
    name: reader
    command: ["bin/sh", "-c", "sleep 3600"] 
    volumeMounts:
    - name: shareddir
      mountPath: /shared  
      readOnly: true  
