apiVersion: v1
kind: Pod
metadata:
  name: debug-sec
spec:
  containers:
  - image: alpine
    name: app
    command: ["sh", "-c", "ping -c 2 google.com & sleep 3600"]
    securityContext:
      readOnlyRootFilesystem: true
      runAsUser: 1000
   
