apiVersion: v1
kind: Pod
metadata:
  name: debug-sec
spec:
  containers:
  - image: nginx
    name: app
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
    volumeMounts:
    - name: cache
      mountPath: /var/cache/nginx/
    - name: run
      mountPath: /run/
  volumes: 
  - name: cache
    emptyDir: {}    
  - name: run
    emptyDir: {}
