apiVersion: v1
kind: Pod
metadata:
  name: sec-drop-all
spec:
  containers:
  - image: alpine
    name: app
    command: ["sleep","3600"]
    securityContext:
      capabilities:
        drop: ["All"]
