apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: correct-label
  template:
    metadata:
      labels:
        app: correct-label
    spec:
      containers:
      - name: nginx
        image: nginx      
