apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-demo
  template:
    metadata:
      labels:
        app: dns-demo
    spec:
      containers:
      - name: nginx
        image: nginx      
